# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-03 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='name',
            field=models.CharField(choices=[('Etsy', 'Etsy'), ('Artfire', 'ArtFire'), ('Handmadeatamazon', 'Handmade at Amazon'), ('Spoonflower', 'Spoonflower')], default='Etsy', max_length=200),
        ),
    ]
