# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsupply',
            options={'verbose_name': 'Supplies Per Item', 'verbose_name_plural': 'Supplies Per Item'},
        ),
        migrations.AlterModelOptions(
            name='supply',
            options={'verbose_name': 'Supply', 'verbose_name_plural': 'Supplies'},
        ),
        migrations.AlterUniqueTogether(
            name='itemsupply',
            unique_together=set([('item', 'supply')]),
        ),
    ]
