# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_auto_20160819_2033'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemsupply',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='itemsupply',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemsupply',
            name='supply',
        ),
        migrations.DeleteModel(
            name='ItemSupply',
        ),
    ]
