# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-02 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='final_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
