# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-03 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20160802_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtsyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etsy_who_made_it', models.CharField(choices=[('i_did', 'I did'), ('collective', 'A member of my shop'), ('someone_else', 'Another company/person')], default='i_did', max_length=12)),
                ('etsy_what_is_it', models.IntegerField(choices=[(0, 'A finished product'), (1, 'A supply or tool to make things')], default=0)),
                ('etsy_when_was_it_made', models.CharField(choices=[('made_to_order', 'Made To Order'), ('2010_2016', '2010 - 2016'), ('2000_2009', '2000s'), ('1997_1999', '1997 - 1999'), ('before_1997', 'Before 1997'), ('1990_1996', '1990 - 1996'), ('1980s', '1980s'), ('1970s', '1970s'), ('1960s', '1960s'), ('1950s', '1950s'), ('1940s', '1940s'), ('1930s', '1930s'), ('1920s', '1920s'), ('1910s', '1910s'), ('1900s', '1900 - 1909')], default='2010_2016', max_length=14)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='etsy_what_is_it',
        ),
        migrations.RemoveField(
            model_name='item',
            name='etsy_when_was_it_made',
        ),
        migrations.RemoveField(
            model_name='item',
            name='etsy_who_made_it',
        ),
        migrations.AddField(
            model_name='etsyitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item'),
        ),
    ]
