# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-03 17:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20160803_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_listed',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 3, 17, 10, 34, 851117, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='dimensions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='materials',
            field=models.TextField(help_text='Comma-separated words or phrases'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.TextField(help_text='Comma-separated words or phrases'),
        ),
    ]
