# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-03 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20160803_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='materials',
        ),
        migrations.AddField(
            model_name='etsyitem',
            name='materials',
            field=models.TextField(default='glass', help_text='Comma-separated words or phrases'),
            preserve_default=False,
        ),
    ]
