# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-03 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20160803_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpoonflowerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_image_name', models.CharField(max_length=200)),
                ('material_type', models.CharField(choices=[('fabric', 'Fabric'), ('wallpaper', 'Wallpaper'), ('giftwrap', 'Gift Wrap')], default='fabric', max_length=10)),
                ('repeat_type', models.CharField(choices=[('basic', 'Basic'), ('halfdrop', 'Half-Drop'), ('halfbrick', 'Half-Brick'), ('center', 'Center'), ('mirror', 'Mirror')], default='basic', help_text="'Basic' is the only option available for wallpaper.", max_length=10)),
                ('design_width', models.IntegerField(blank=True, help_text='In inches.', null=True)),
                ('design_height', models.IntegerField(blank=True, help_text='In inches.', null=True)),
                ('dpi', models.IntegerField(blank=True, default=150, null=True)),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
            ],
        ),
    ]
