# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-03 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_spoonfloweritem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='item',
        ),
        migrations.AddField(
            model_name='etsyitem',
            name='category_name',
            field=models.CharField(blank=True, help_text='Your store category', max_length=60, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ItemCategory',
        ),
    ]
