# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_auto_20160819_2041'),
        ('inventory', '0012_auto_20160803_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Number of individual units used in item')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.Supply')),
            ],
            options={
                'verbose_name': 'Supplies Per Item',
                'verbose_name_plural': 'Supplies Per Item',
            },
        ),
        migrations.AlterUniqueTogether(
            name='itemsupply',
            unique_together=set([('item', 'supply')]),
        ),
    ]
