# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20160819_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='min_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum Cost'),
        ),
    ]
